### ISSUE TITLE
Correct Error Code Causing Critical error

### ISSUE THREAD

**Issue by daknoxy** [ItinerisLtd/gf-loqate-bank-verification#35] opened 2020-11-06 09:59 UTC
Hi Tang

We did have the Php which was fixed but below is error code relating to the oplugin
An error of type E_ERROR was caused in line 16 of the file /home2/crag/public_html/wp-content/plugins/gf_pcapredict/gf_pcapredict.php. Error message: Uncaught Error: Call to undefined function is_plugin_active() in /home2/crag/public_html/wp-content/plugins/gf_pcapredict/gf_pcapredict.php:16
Stack trace:
#0 /home2/crag/public_html/wp-settings.php(362): include_once()
#1 /home2/crag/public_html/wp-config.php(97): require_once('/home2/crag/pub...')
#2 /home2/crag/public_html/wp-load.php(37): require_once('/home2/crag/pub...')
#3 /home2/crag/public_html/wp-admin/admin.php(34): require_once('/home2/crag/pub...')
#4 {main}
thrown

**Comment by tangrufus** [comment] 2020-11-06 10:05
duplicate of https://github.com/ItinerisLtd/gf-loqate-bank-verification/issues/34

**Closed as completed by tangrufus** 2020-11-06 10:05 UTC
Labels: duplicate
